import type { LotRect } from "./grid3d";

/**
 * Declarative scene composition data.
 *
 * A scene is architecture first: an EnvironmentSpec establishes the ground,
 * platforms, walls, stairs, and zones — the place itself. Catalog pieces then
 * populate it lot by lot. The spec is plain data so scenes can be authored,
 * generated by the composer, or (later) round-tripped through tools.
 */

/**
 * Ground materials — a material ECOSYSTEM, not one texture. Themes compose
 * these into palettes (primary strips + secondary/accent/rare patches).
 */
export type PlatformMaterial =
  // structural originals
  | "grass" | "stone" | "wood" | "sand" | "road" | "tile"
  // earth + vegetation
  | "grass-dark" | "grass-dry" | "dirt" | "moss" | "mud"
  // stonework
  | "stone-dark" | "cobble" | "stone-mossy"
  // arid
  | "sand-dark" | "earth-cracked"
  // cold
  | "snow" | "ice"
  // volcanic
  | "ash" | "rock-dark" | "ember"
  // whimsical
  | "candy-pink" | "candy-mint" | "candy-cream" | "candy-lilac"
  // eerie
  | "shadow-purple";

/** Every ground material, for tool-input validation and palette listings. */
export const GROUND_MATERIALS: PlatformMaterial[] = [
  "grass", "stone", "wood", "sand", "road", "tile",
  "grass-dark", "grass-dry", "dirt", "moss", "mud",
  "stone-dark", "cobble", "stone-mossy",
  "sand-dark", "earth-cracked",
  "snow", "ice",
  "ash", "rock-dark", "ember",
  "candy-pink", "candy-mint", "candy-cream", "candy-lilac",
  "shadow-purple",
];

export type PlatformSpec = {
  id: string;
  rect: LotRect;
  /** Elevation in whole levels — world y of the deck is level * ELEV. */
  level: number;
  material: PlatformMaterial;
  /**
   * A thin bed laid ON another platform of the same level (a garden bed, a
   * rug of grass). Renders slightly raised so same-level decks never z-fight.
   */
  inset?: boolean;
};

export type WallSide = "n" | "s" | "e" | "w";

/**
 * A wall runs along one edge of a run of lots: `dir: "h"` walls sit on the
 * north or south edge of lots (c..c+len-1, r); `dir: "v"` walls sit on the
 * east or west edge of lots (c, r..r+len-1). `openings` are lot offsets along
 * the run left as doorways.
 */
export type WallSpec = {
  id: string;
  c: number;
  r: number;
  len: number;
  dir: "h" | "v";
  side: WallSide;
  /** Wall height in world units. */
  height: number;
  openings?: number[];
};

export type StairSpec = {
  id: string;
  /** The lot the stair occupies — reserved, nothing can be placed on it. */
  at: { col: number; row: number };
  /** Direction you face walking UP the stair. */
  dir: WallSide;
  fromLevel: number;
  toLevel: number;
};

export type PathSpec = {
  id: string;
  cells: { col: number; row: number }[];
};

export type WaterSpec = {
  id: string;
  rect: LotRect;
  /** Water surface sits a bit below this platform level's deck. */
  level: number;
};

export type ZoneType =
  | "plaza"
  | "home"
  | "market"
  | "garden"
  | "harbor"
  | "street"
  | "arcade"
  | "workshop"
  | "keep"
  | "lab"
  | "camp"
  | "skyline";

export type ZoneSpec = {
  id: string;
  type: ZoneType;
  label: string;
  rect: LotRect;
  level: number;
  /** The zone's visual anchor — clusters orient toward it. */
  focal?: { col: number; row: number };
};

/** One cell of themed ground overriding its platform's base material. */
export type GroundCell = { col: number; row: number; m: PlatformMaterial };

/** Seeded water tone — deep, mid, bright, or dark pockets. */
export type WaterTone = 0 | 1 | 2 | 3;

/** One lot of water with a painted tone override. */
export type WaterCell = { col: number; row: number; t: WaterTone };

export type EnvironmentSpec = {
  platforms: PlatformSpec[];
  walls: WallSpec[];
  stairs: StairSpec[];
  paths: PathSpec[];
  water: WaterSpec[];
  zones: ZoneSpec[];
  /** The theme this environment was styled with (lib/composition/themes.ts). */
  themeId?: string;
  /** Themed walk material for path cells. */
  pathMaterial?: PlatformMaterial;
  /** Seeded material patches — intentional regions, never per-block noise. */
  ground?: GroundCell[];
  /** Seeded water-tone patches — same blob logic as ground, for harbors. */
  waterCells?: WaterCell[];
};

export function emptyEnvironment(): EnvironmentSpec {
  return { platforms: [], walls: [], stairs: [], paths: [], water: [], zones: [] };
}
