import type { LotRect } from "./grid3d";

/**
 * Declarative scene composition data.
 *
 * A scene is architecture first: an EnvironmentSpec establishes the ground,
 * platforms, walls, stairs, and zones — the place itself. Catalog pieces then
 * populate it lot by lot. The spec is plain data so scenes can be authored,
 * generated by the composer, or (later) round-tripped through tools.
 */

export type PlatformMaterial = "grass" | "stone" | "wood" | "sand" | "road" | "tile";

export type PlatformSpec = {
  id: string;
  rect: LotRect;
  /** Elevation in whole levels — world y of the deck is level * ELEV. */
  level: number;
  material: PlatformMaterial;
  /**
   * A thin bed laid ON another platform of the same level (a garden bed, a
   * rug of grass). Renders slightly raised so same-level decks never z-fight.
   */
  inset?: boolean;
};

export type WallSide = "n" | "s" | "e" | "w";

/**
 * A wall runs along one edge of a run of lots: `dir: "h"` walls sit on the
 * north or south edge of lots (c..c+len-1, r); `dir: "v"` walls sit on the
 * east or west edge of lots (c, r..r+len-1). `openings` are lot offsets along
 * the run left as doorways.
 */
export type WallSpec = {
  id: string;
  c: number;
  r: number;
  len: number;
  dir: "h" | "v";
  side: WallSide;
  /** Wall height in world units. */
  height: number;
  openings?: number[];
};

export type StairSpec = {
  id: string;
  /** The lot the stair occupies — reserved, nothing can be placed on it. */
  at: { col: number; row: number };
  /** Direction you face walking UP the stair. */
  dir: WallSide;
  fromLevel: number;
  toLevel: number;
};

export type PathSpec = {
  id: string;
  cells: { col: number; row: number }[];
};

export type WaterSpec = {
  id: string;
  rect: LotRect;
  /** Water surface sits a bit below this platform level's deck. */
  level: number;
};

export type ZoneType =
  | "plaza"
  | "home"
  | "market"
  | "garden"
  | "harbor"
  | "street"
  | "arcade"
  | "workshop"
  | "keep"
  | "lab"
  | "camp"
  | "skyline";

export type ZoneSpec = {
  id: string;
  type: ZoneType;
  label: string;
  rect: LotRect;
  level: number;
  /** The zone's visual anchor — clusters orient toward it. */
  focal?: { col: number; row: number };
};

export type EnvironmentSpec = {
  platforms: PlatformSpec[];
  walls: WallSpec[];
  stairs: StairSpec[];
  paths: PathSpec[];
  water: WaterSpec[];
  zones: ZoneSpec[];
};

export function emptyEnvironment(): EnvironmentSpec {
  return { platforms: [], walls: [], stairs: [], paths: [], water: [], zones: [] };
}
